title: Settings
fields:
  -
    handle: menu_title
    field:
      type: text
      display: 'Menu title'
      localizable: true
  -
    handle: template
    field:
      type: template
      display: Template
      folder: templates
      localizable: false
  -
    handle: layout
    field:
      type: template
      display: Layout
      folder: templates
      localizable: false
  -
    handle: container_padding_top
    field:
      default: true
      type: toggle
      display: 'Container padding top'
      localizable: false
      width: 50
  -
    handle: container_padding_bottom
    field:
      default: true
      type: toggle
      display: 'Container padding bottom'
      localizable: false
      width: 50
